# tell docker what version of the docker-compose.yml we're using
version: '3.7'

# define the network
#networks:
#  web-network:

services:
  # web server
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # app
      - ..:/usr/share/nginx/painter
      # nginx configs
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
    links:
      - php-fpm:__DOCKER_PHP_FPM__

  # php-fpm
  php-fpm:
    build: ./php-fpm
    ports:
      - "9000"
    volumes:
      - ..:/usr/share/nginx/painter
      # Your php.ini
      - ./php-fpm/php.ini-production:/usr/local/etc/php/php.ini:ro
    # environment:
      # Set your APP env variables here:
      # - APP_KEY=
      # - DB_HOST=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    links:
      - mysql:mysql

  # database
  mysql:
    image: mysql:latest
    ports:
      # Allow client to access 3306
      - "3306:3306"
    volumes:
      # NOTE: your data will be stored in ./mysql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
