index:
    path: /
    controller: App\Controller\IndexController::index

catalog:
    path: /catalog
    controller: App\Controller\CatalogController::index

catalog_path:
    path: /catalog/path/{path}
    controller: App\Controller\CatalogController::index

catalog_add_directory:
    path: /catalog/addDirectory
    controller: App\Controller\CatalogController::addDirectory
    methods: POST
